---
title: "Model"
author: "Jieun Park"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
# Load graph from Pajek
big_component_data <- read_graph("big_component.graphml", format = "gml")

# simplify the graph
gRC <- simplify(big_component_data)

install.packages("gender")
library(gender)

V(gRC)$authname <- data$authname


unique_data <- data %>%
  select(authid, authname) %>%
  distinct()

# authname에서 첫 번째 이름만 남기고 나머지는 제거합니다.
unique_data <- unique_data %>%
  mutate(firstname = sub(" .*", "", authname))

# 그래프의 authid와 일치하는 firstname을 가져옵니다.
firstname_vector <- V(gRC)$name %>%
  as.character() %>%
  match(unique_data$authid) %>%
  unique_data$firstname[.]

# 그래프에 firstname 속성을 추가합니다.
V(gRC)$authname <- firstname_vector

# gender categorizing
gender <- gender(V(gRC)$authname)

```

```{r}
library(igraph)
library(dplyr)
library(gender)
library(stargazer)

collaboration_count <- degree(gRC, mode = "all")


discipline <- V(gRC)$discipline


author_papers <- data %>%
  group_by(authid) %>%
  summarise(n_papers = n())


authnames <- unique(data.frame(authid = as.character(V(gRC)$name), authname = V(gRC)$authname))
gender_data <- gender(unique(authnames$authname), method = "ssa") %>%
  select(name, gender)


unique_data <- authnames %>%
  mutate(firstname = sub(" .*", "", authname))


unique_data <- unique_data %>%
  left_join(gender_data, by = c("firstname" = "name"))

node_data <- data.frame(
  authid = as.character(V(gRC)$name),  
  collaboration_count = collaboration_count,
  discipline = discipline,
  stringsAsFactors = FALSE
)


author_papers <- author_papers %>%
  mutate(authid = as.character(authid))  

node_data <- node_data %>%
  left_join(author_papers, by = "authid")


node_data <- node_data %>%
  left_join(unique_data, by = "authid")


node_data$discipline <- as.factor(node_data$discipline)
node_data$gender <- as.factor(node_data$gender)


node_data <- node_data %>%
  filter(!is.na(collaboration_count) & !is.na(discipline) & !is.na(n_papers) & !is.na(gender))


levels(node_data$discipline)
levels(node_data$gender)

```

### Model 1

```{r}
model <- lm(collaboration_count ~ discipline + n_papers + gender, data = node_data)

# 결과 요약
summary(model)

stargazer(model, type = "text", out = "model_summary.txt")

# Save the node_data dataframe as a CSV file
write.csv(node_data, "node_data.csv", row.names = FALSE)
```


### Model 2

```{r}
model <- lm(log(collaboration_count) ~ discipline + log(n_papers) + gender, data = node_data)

summary(model)
```


### Model 3

```{r}

library(ggplot2)
library(readr)
library(dplyr)

node_data 

node_data <- node_data %>%
  mutate(collab_percentage = (collaboration_count / n_papers) * 100)

# Fit the linear regression model
model <- lm(collab_percentage ~ discipline + log(n_papers) + gender, data = node_data)

# Display the summary of the model
summary(model)

```



